INSERT INTO currencies (id, code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES
(1, 'USD', 'US Dollar', '$', '$', 2, 0, 'US dollars'),
(2, 'CAD', 'Canadian Dollar', 'CA$', '$', 2, 0, 'Canadian dollars'),
(3, 'EUR', 'Euro', '€', '€', 2, 0, 'euros'),
(4, 'AED', 'United Arab Emirates Dirham', 'AED', 'د.إ.‏', 2, 0, 'UAE dirhams'),
(5, 'AFN', 'Afghan Afghani', 'Af', '؋', 0, 0, 'Afghan Afghanis'),
(6, 'ALL', 'Albanian Lek', 'ALL', 'Lek', 0, 0, 'Albanian lekë'),
(7, 'AMD', 'Armenian Dram', 'AMD', 'դր.', 0, 0, 'Armenian drams'),
(8, 'ARS', 'Argentine Peso', 'AR$', '$', 2, 0, 'Argentine pesos'),
(9, 'AUD', 'Australian Dollar', 'AU$', '$', 2, 0, 'Australian dollars'),
(10, 'AZN', 'Azerbaijani Manat', 'man.', 'ман.', 2, 0, 'Azerbaijani manats'),
(11, 'BAM', 'Bosnia-Herzegovina Convertible Mark', 'KM', 'KM', 2, 0, 'Bosnia-Herzegovina convertible marks'),
(12, 'BDT', 'Bangladeshi Taka', 'Tk', '৳', 2, 0, 'Bangladeshi takas'),
(13, 'BGN', 'Bulgarian Lev', 'BGN', 'лв.', 2, 0, 'Bulgarian leva'),
(14, 'BHD', 'Bahraini Dinar', 'BD', 'د.ب.‏', 3, 0, 'Bahraini dinars'),
(15, 'BIF', 'Burundian Franc', 'FBu', 'FBu', 0, 0, 'Burundian francs'),
(16, 'BND', 'Brunei Dollar', 'BN$', '$', 2, 0, 'Brunei dollars'),
(17, 'BOB', 'Bolivian Boliviano', 'Bs', 'Bs', 2, 0, 'Bolivian bolivianos'),
(18, 'BRL', 'Brazilian Real', 'R$', 'R$', 2, 0, 'Brazilian reals'),
(19, 'BWP', 'Botswanan Pula', 'BWP', 'P', 2, 0, 'Botswanan pulas'),
(20, 'BYN', 'Belarusian Ruble', 'Br', 'руб.', 2, 0, 'Belarusian rubles'),
(21, 'BZD', 'Belize Dollar', 'BZ$', '$', 2, 0, 'Belize dollars'),
(22, 'CDF', 'Congolese Franc', 'CDF', 'FrCD', 2, 0, 'Congolese francs'),
(23, 'CHF', 'Swiss Franc', 'CHF', 'CHF', 2, 0.05, 'Swiss francs'),
(24, 'CLP', 'Chilean Peso', 'CL$', '$', 0, 0, 'Chilean pesos'),
(25, 'CNY', 'Chinese Yuan', 'CN¥', 'CN¥', 2, 0, 'Chinese yuan'),
(26, 'COP', 'Colombian Peso', 'CO$', '$', 0, 0, 'Colombian pesos'),
(27, 'CRC', 'Costa Rican Colón', '₡', '₡', 0, 0, 'Costa Rican colóns'),
(28, 'CVE', 'Cape Verdean Escudo', 'CV$', 'CV$', 2, 0, 'Cape Verdean escudos'),
(29, 'CZK', 'Czech Republic Koruna', 'Kč', 'Kč', 2, 0, 'Czech Republic korunas'),
(30, 'DJF', 'Djiboutian Franc', 'Fdj', 'Fdj', 0, 0, 'Djiboutian francs'),
(31, 'DKK', 'Danish Krone', 'Dkr', 'kr', 2, 0, 'Danish kroner'),
(32, 'DOP', 'Dominican Peso', 'RD$', 'RD$', 2, 0, 'Dominican pesos'),
(33, 'DZD', 'Algerian Dinar', 'DA', 'د.ج.‏', 2, 0, 'Algerian dinars'),
(34, 'EEK', 'Estonian Kroon', 'Ekr', 'kr', 2, 0, 'Estonian kroons'),
(35, 'EGP', 'Egyptian Pound', 'EGP', 'ج.م.‏', 2, 0, 'Egyptian pounds'),
(36, 'ERN', 'Eritrean Nakfa', 'Nfk', 'Nfk', 2, 0, 'Eritrean nakfas'),
(37, 'ETB', 'Ethiopian Birr', 'Br', 'Br', 2, 0, 'Ethiopian birrs'),
(38, 'GBP', 'British Pound Sterling', '£', '£', 2, 0, 'British pounds sterling'),
(39, 'GEL', 'Georgian Lari', 'GEL', 'GEL', 2, 0, 'Georgian laris'),
(40, 'GHS', 'Ghanaian Cedi', 'GH₵', 'GH₵', 2, 0, 'Ghanaian cedis'),
(41, 'GNF', 'Guinean Franc', 'FG', 'FG', 0, 0, 'Guinean francs'),
(42, 'GTQ', 'Guatemalan Quetzal', 'GTQ', 'Q', 2, 0, 'Guatemalan quetzals'),
(43, 'HKD', 'Hong Kong Dollar', 'HK$', '$', 2, 0, 'Hong Kong dollars'),
(44, 'HNL', 'Honduran Lempira', 'HNL', 'L', 2, 0, 'Honduran lempiras'),
(45, 'HRK', 'Croatian Kuna', 'kn', 'kn', 2, 0, 'Croatian kunas'),
(46, 'HUF', 'Hungarian Forint', 'Ft', 'Ft', 0, 0, 'Hungarian forints'),
(47, 'IDR', 'Indonesian Rupiah', 'Rp', 'Rp', 0, 0, 'Indonesian rupiahs'),
(48, 'ILS', 'Israeli New Sheqel', '₪', '₪', 2, 0, 'Israeli new sheqels'),
(49, 'INR', 'Indian Rupee', 'Rs', 'টকা', 2, 0, 'Indian rupees'),
(50, 'IQD', 'Iraqi Dinar', 'IQD', 'د.ع.‏', 0, 0, 'Iraqi dinars'),
(51, 'IRR', 'Iranian Rial', 'IRR', '﷼', 0, 0, 'Iranian rials'),
(52, 'ISK', 'Icelandic Króna', 'Ikr', 'kr', 0, 0, 'Icelandic krónur'),
(53, 'JMD', 'Jamaican Dollar', 'J$', '$', 2, 0, 'Jamaican dollars'),
(54, 'JOD', 'Jordanian Dinar', 'JD', 'د.أ.‏', 3, 0, 'Jordanian dinars'),
(55, 'JPY', 'Japanese Yen', '¥', '￥', 0, 0, 'Japanese yen'),
(56, 'KES', 'Kenyan Shilling', 'Ksh', 'Ksh', 2, 0, 'Kenyan shillings'),
(57, 'KHR', 'Cambodian Riel', 'KHR', '៛', 2, 0, 'Cambodian riels'),
(58, 'KMF', 'Comorian Franc', 'CF', 'FC', 0, 0, 'Comorian francs'),
(59, 'KRW', 'South Korean Won', '₩', '₩', 0, 0, 'South Korean won'),
(60, 'KWD', 'Kuwaiti Dinar', 'KD', 'د.ك.‏', 3, 0, 'Kuwaiti dinars'),
(61, 'KZT', 'Kazakhstani Tenge', 'KZT', 'тңг.', 2, 0, 'Kazakhstani tenges'),
(62, 'LBP', 'Lebanese Pound', 'LB£', 'ل.ل.‏', 0, 0, 'Lebanese pounds'),
(63, 'LKR', 'Sri Lankan Rupee', 'SLRs', 'SL Re', 2, 0, 'Sri Lankan rupees'),
(64, 'LTL', 'Lithuanian Litas', 'Lt', 'Lt', 2, 0, 'Lithuanian litai'),
(65, 'LVL', 'Latvian Lats', 'Ls', 'Ls', 2, 0, 'Latvian lati'),
(66, 'LYD', 'Libyan Dinar', 'LD', 'د.ل.‏', 3, 0, 'Libyan dinars'),
(67, 'MAD', 'Moroccan Dirham', 'MAD', 'د.م.‏', 2, 0, 'Moroccan dirhams'),
(68, 'MDL', 'Moldovan Leu', 'MDL', 'MDL', 2, 0, 'Moldovan lei'),
(69, 'MGA', 'Malagasy Ariary', 'MGA', 'MGA', 0, 0, 'Malagasy Ariaries'),
(70, 'MKD', 'Macedonian Denar', 'MKD', 'MKD', 2, 0, 'Macedonian denari'),
(71, 'MMK', 'Myanma Kyat', 'MMK', 'K', 0, 0, 'Myanma kyats'),
(72, 'MOP', 'Macanese Pataca', 'MOP$', 'MOP$', 2, 0, 'Macanese patacas'),
(73, 'MUR', 'Mauritian Rupee', 'MURs', 'MURs', 0, 0, 'Mauritian rupees'),
(74, 'MXN', 'Mexican Peso', 'MX$', '$', 2, 0, 'Mexican pesos'),
(75, 'MYR', 'Malaysian Ringgit', 'RM', 'RM', 2, 0, 'Malaysian ringgits'),
(76, 'MZN', 'Mozambican Metical', 'MTn', 'MTn', 2, 0, 'Mozambican meticals'),
(77, 'NAD', 'Namibian Dollar', 'N$', 'N$', 2, 0, 'Namibian dollars'),
(78, 'NGN', 'Nigerian Naira', '₦', '₦', 2, 0, 'Nigerian nairas'),
(79, 'NIO', 'Nicaraguan Córdoba', 'C$', 'C$', 2, 0, 'Nicaraguan córdobas'),
(80, 'NOK', 'Norwegian Krone', 'Nkr', 'kr', 2, 0, 'Norwegian kroner'),
(81, 'NPR', 'Nepalese Rupee', 'NPRs', 'नेरू', 2, 0, 'Nepalese rupees'),
(82, 'NZD', 'New Zealand Dollar', 'NZ$', '$', 2, 0, 'New Zealand dollars'),
(83, 'OMR', 'Omani Rial', 'OMR', 'ر.ع.‏', 3, 0, 'Omani rials'),
(84, 'PAB', 'Panamanian Balboa', 'B/.', 'B/.', 2, 0, 'Panamanian balboas'),
(85, 'PEN', 'Peruvian Nuevo Sol', 'S/.', 'S/.', 2, 0, 'Peruvian nuevos soles'),
(86, 'PHP', 'Philippine Peso', '₱', '₱', 2, 0, 'Philippine pesos'),
(87, 'PKR', 'Pakistani Rupee', 'PKRs', '₨', 0, 0, 'Pakistani rupees'),
(88, 'PLN', 'Polish Zloty', 'zł', 'zł', 2, 0, 'Polish zlotys'),
(89, 'PYG', 'Paraguayan Guarani', '₲', '₲', 0, 0, 'Paraguayan guaranis'),
(90, 'QAR', 'Qatari Rial', 'QR', 'ر.ق.‏', 2, 0, 'Qatari rials'),
(91, 'RON', 'Romanian Leu', 'RON', 'RON', 2, 0, 'Romanian lei'),
(92, 'RSD', 'Serbian Dinar', 'din.', 'дин.', 0, 0, 'Serbian dinars'),
(93, 'RUB', 'Russian Ruble', 'RUB', '₽.', 2, 0, 'Russian rubles'),
(94, 'RWF', 'Rwandan Franc', 'RWF', 'FR', 0, 0, 'Rwandan francs'),
(95, 'SAR', 'Saudi Riyal', 'SR', 'ر.س.‏', 2, 0, 'Saudi riyals'),
(96, 'SDG', 'Sudanese Pound', 'SDG', 'SDG', 2, 0, 'Sudanese pounds'),
(97, 'SEK', 'Swedish Krona', 'Skr', 'kr', 2, 0, 'Swedish kronor'),
(98, 'SGD', 'Singapore Dollar', 'S$', '$', 2, 0, 'Singapore dollars'),
(99, 'SOS', 'Somali Shilling', 'Ssh', 'Ssh', 0, 0, 'Somali shillings'),
(100, 'SYP', 'Syrian Pound', 'SY£', 'ل.س.‏', 0, 0, 'Syrian pounds'),
(101, 'THB', 'Thai Baht', '฿', '฿', 2, 0, 'Thai baht'),
(102, 'TND', 'Tunisian Dinar', 'DT', 'د.ت.‏', 3, 0, 'Tunisian dinars'),
(103, 'TOP', 'Tongan Paʻanga', 'T$', 'T$', 2, 0, 'Tongan paʻanga'),
(104, 'TRY', 'Turkish Lira', 'TL', 'TL', 2, 0, 'Turkish Lira'),
(105, 'TTD', 'Trinidad and Tobago Dollar', 'TT$', '$', 2, 0, 'Trinidad and Tobago dollars'),
(106, 'TWD', 'New Taiwan Dollar', 'NT$', 'NT$', 2, 0, 'New Taiwan dollars'),
(107, 'TZS', 'Tanzanian Shilling', 'TSh', 'TSh', 0, 0, 'Tanzanian shillings'),
(108, 'UAH', 'Ukrainian Hryvnia', '₴', '₴', 2, 0, 'Ukrainian hryvnias'),
(109, 'UGX', 'Ugandan Shilling', 'USh', 'USh', 0, 0, 'Ugandan shillings'),
(110, 'UYU', 'Uruguayan Peso', '$U', '$', 2, 0, 'Uruguayan pesos'),
(111, 'UZS', 'Uzbekistan Som', 'UZS', 'UZS', 0, 0, 'Uzbekistan som'),
(112, 'VEF', 'Venezuelan Bolívar', 'Bs.F.', 'Bs.F.', 2, 0, 'Venezuelan bolívars'),
(113, 'VND', 'Vietnamese Dong', '₫', '₫', 0, 0, 'Vietnamese dong'),
(114, 'XAF', 'CFA Franc BEAC', 'FCFA', 'FCFA', 0, 0, 'CFA francs BEAC'),
(115, 'XOF', 'CFA Franc BCEAO', 'CFA', 'CFA', 0, 0, 'CFA francs BCEAO'),
(116, 'YER', 'Yemeni Rial', 'YR', 'ر.ي.‏', 0, 0, 'Yemeni rials'),
(117, 'ZAR', 'South African Rand', 'R', 'R', 2, 0, 'South African rand'),
(118, 'ZMK', 'Zambian Kwacha', 'ZK', 'ZK', 0, 0, 'Zambian kwachas'),
(119, 'ZWL', 'Zimbabwean Dollar', 'ZWL$', 'ZWL$', 0, 0, 'Zimbabwean Dollar');
