
CREATE TABLE IF NOT EXISTS "countries" (
	"id" SMALLINT NOT NULL COMMENT '',
	"name" CHARACTER VARYING(250) NULL DEFAULT NULL COMMENT '',
	"code" CHARACTER VARYING(5) NULL DEFAULT NULL COMMENT '',
	"native" CHARACTER VARYING(250) NULL DEFAULT NULL COMMENT '',
	"phone" SMALLINT[] NULL DEFAULT NULL COMMENT '',
	"continent" SMALLINT NULL DEFAULT NULL COMMENT '',
	"capital" CHARACTER VARYING(250) NULL DEFAULT NULL COMMENT '',
	"currencies" SMALLINT[] NULL DEFAULT NULL COMMENT '',
	"languages" SMALLINT[] NULL DEFAULT NULL COMMENT '',
	"main_cities" INTEGER[] NULL DEFAULT NULL COMMENT '',
	"parent_country" SMALLINT NOT NULL DEFAULT '0'::smallint COMMENT '',
	PRIMARY KEY ("id")
);